# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10mqLPRrVanvkmeCKNwYIItQ1rqk2ec2U
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("apple.csv")

print(df.head())
print(df.shape)
print(df.info())
print(df.isnull().sum())

# Remove rows where Date is missing
df = df.dropna(subset=["Date"])

# Convert Date to datetime
df["Date"] = pd.to_datetime(df["Date"])

# Numerical columns
numeric_cols = ["Close", "High", "Low", "Open", "Volume"]

# Convert columns to numeric
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Remove invalid rows
df = df.dropna()

# Sort by date
df = df.sort_values("Date").reset_index(drop=True)

# Remove duplicate dates
df = df.drop_duplicates(subset="Date")

print(df.head())
print(df.tail())
print(df.shape)
print(df.info())
print(df.isnull().sum())

print("Rows:", len(df))
print("Start:", df["Date"].min())
print("End:", df["Date"].max())
print("Duplicates:", df["Date"].duplicated().sum())
print("Missing values:\n", df.isnull().sum())

print(df.describe())

start_price = df["Close"].iloc[0]
end_price = df["Close"].iloc[-1]

change = ((end_price - start_price) / start_price) * 100

print("Starting Price:", round(start_price, 2))
print("Ending Price:", round(end_price, 2))
print("Overall Change:", round(change, 2), "%")

plt.figure(figsize=(12, 5))

plt.plot(df["Date"], df["Close"])

plt.title("AAPL Closing Price (2020–2025)")
plt.xlabel("Date")
plt.ylabel("Closing Price ($)")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 5))

plt.plot(df["Date"], df["Volume"])

plt.title("AAPL Trading Volume (2020–2025)")
plt.xlabel("Date")
plt.ylabel("Volume")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

prices = df[["Close"]].values

print(prices.shape)

from sklearn.preprocessing import MinMaxScaler

# 80% training, 20% testing
split = int(len(prices) * 0.8)

train_prices = prices[:split]
test_prices = prices[split:]

print("Training data:", train_prices.shape)
print("Testing data:", test_prices.shape)

scaler = MinMaxScaler(feature_range=(0, 1))

train_scaled = scaler.fit_transform(train_prices)

# Include previous 30 days for creating test sequences
lookback = 30

test_input = prices[split - lookback:]

test_scaled = scaler.transform(test_input)

X_train = []
y_train = []

for i in range(lookback, len(train_scaled)):
    X_train.append(train_scaled[i-lookback:i, 0])
    y_train.append(train_scaled[i, 0])

X_test = []
y_test = []

for i in range(lookback, len(test_scaled)):
    X_test.append(test_scaled[i-lookback:i, 0])
    y_test.append(test_scaled[i, 0])

X_train = np.array(X_train)
y_train = np.array(y_train)

X_test = np.array(X_test)
y_test = np.array(y_test)

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X_train = X_train.reshape(
    X_train.shape[0],
    X_train.shape[1],
    1
)

X_test = X_test.reshape(
    X_test.shape[0],
    X_test.shape[1],
    1
)

print("Final X_train:", X_train.shape)
print("Final X_test:", X_test.shape)

import tensorflow as tf

print("TensorFlow version:", tf.__version__)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential([
    LSTM(50, return_sequences=True, input_shape=(30, 1)),
    Dropout(0.2),

    LSTM(50),
    Dropout(0.2),

    Dense(25),
    Dense(1)
])

model.compile(
    optimizer="adam",
    loss="mean_squared_error"
)

model.summary()

history = model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.1,
    shuffle=False
)

plt.figure(figsize=(10, 5))

plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")

plt.title("LSTM Training and Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.tight_layout()
plt.show()

predictions = model.predict(X_test)

print("Prediction shape:", predictions.shape)

predicted_prices = scaler.inverse_transform(predictions)

actual_prices = scaler.inverse_transform(
    y_test.reshape(-1, 1)
)

print("First 5 predicted prices:")
print(predicted_prices[:5])

print("\nFirst 5 actual prices:")
print(actual_prices[:5])

from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(
    actual_prices,
    predicted_prices
)

rmse = np.sqrt(
    mean_squared_error(
        actual_prices,
        predicted_prices
    )
)

print("MAE:", round(mae, 2))
print("RMSE:", round(rmse, 2))

plt.figure(figsize=(12, 5))

plt.plot(actual_prices, label="Actual Price")
plt.plot(predicted_prices, label="Predicted Price")

plt.title("AAPL Actual vs Predicted Closing Price")
plt.xlabel("Trading Days")
plt.ylabel("Closing Price ($)")
plt.legend()

plt.tight_layout()
plt.show()

# Naive prediction:
# Tomorrow's price = today's price

naive_predictions = df["Close"].iloc[split-1:-1].values

print("Naive predictions:", naive_predictions.shape)
print("Actual test prices:", actual_prices.shape)

naive_mae = mean_absolute_error(
    actual_prices.flatten(),
    naive_predictions
)

naive_rmse = np.sqrt(
    mean_squared_error(
        actual_prices.flatten(),
        naive_predictions
    )
)

print("Naive Baseline MAE:", round(naive_mae, 2))
print("Naive Baseline RMSE:", round(naive_rmse, 2))

print("Model Comparison")
print("---------------------------")
print("LSTM MAE:          ", round(mae, 2))
print("Naive Baseline MAE:", round(naive_mae, 2))
print()
print("LSTM RMSE:          ", round(rmse, 2))
print("Naive Baseline RMSE:", round(naive_rmse, 2))

mae_difference = ((mae - naive_mae) / naive_mae) * 100
rmse_difference = ((rmse - naive_rmse) / naive_rmse) * 100

print("LSTM MAE vs Baseline:", round(mae_difference, 2), "% higher")
print("LSTM RMSE vs Baseline:", round(rmse_difference, 2), "% higher")

from sklearn.preprocessing import MinMaxScaler
import numpy as np

features = ["Open", "High", "Low", "Close", "Volume"]

data = df[features].values

# Same 80/20 split
split = int(len(data) * 0.8)

train_data = data[:split]
test_data = data[split:]

# Scale using training data only
scaler_multi = MinMaxScaler(feature_range=(0, 1))

train_scaled = scaler_multi.fit_transform(train_data)
test_input = data[split - lookback:]
test_scaled = scaler_multi.transform(test_input)

print("Train:", train_scaled.shape)
print("Test:", test_scaled.shape)

X_train_multi = []
y_train_multi = []

for i in range(lookback, len(train_scaled)):
    X_train_multi.append(
        train_scaled[i-lookback:i, :]
    )
    y_train_multi.append(
        train_scaled[i, 3]   # Close is column 3
    )


X_test_multi = []
y_test_multi = []

for i in range(lookback, len(test_scaled)):
    X_test_multi.append(
        test_scaled[i-lookback:i, :]
    )
    y_test_multi.append(
        test_scaled[i, 3]
    )


X_train_multi = np.array(X_train_multi)
y_train_multi = np.array(y_train_multi)

X_test_multi = np.array(X_test_multi)
y_test_multi = np.array(y_test_multi)

print("X_train:", X_train_multi.shape)
print("y_train:", y_train_multi.shape)
print("X_test:", X_test_multi.shape)
print("y_test:", y_test_multi.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model_multi = Sequential([
    LSTM(50, return_sequences=True, input_shape=(30, 5)),
    Dropout(0.2),

    LSTM(50),
    Dropout(0.2),

    Dense(25),
    Dense(1)
])

model_multi.compile(
    optimizer="adam",
    loss="mean_squared_error"
)

model_multi.summary()

history_multi = model_multi.fit(
    X_train_multi,
    y_train_multi,
    epochs=30,
    batch_size=32,
    validation_split=0.1,
    shuffle=False
)

predictions_multi = model_multi.predict(X_test_multi)

print("Prediction shape:", predictions_multi.shape)

close_min = scaler_multi.data_min_[3]
close_max = scaler_multi.data_max_[3]

predicted_multi = (
    predictions_multi * (close_max - close_min)
    + close_min
)

actual_multi = (
    y_test_multi.reshape(-1, 1) * (close_max - close_min)
    + close_min
)

print("First 5 predictions:")
print(predicted_multi[:5])

print("\nFirst 5 actual prices:")
print(actual_multi[:5])

from sklearn.metrics import mean_absolute_error, mean_squared_error

mae_multi = mean_absolute_error(
    actual_multi,
    predicted_multi
)

rmse_multi = np.sqrt(
    mean_squared_error(
        actual_multi,
        predicted_multi
    )
)

print("Multivariate LSTM MAE:", round(mae_multi, 2))
print("Multivariate LSTM RMSE:", round(rmse_multi, 2))

print("MODEL COMPARISON")
print("=" * 45)

print(f"Naive Baseline     MAE:  ${naive_mae:.2f}")
print(f"Univariate LSTM    MAE:  ${mae:.2f}")
print(f"Multivariate LSTM  MAE:  ${mae_multi:.2f}")

print()

print(f"Naive Baseline     RMSE: ${naive_rmse:.2f}")
print(f"Univariate LSTM    RMSE: ${rmse:.2f}")
print(f"Multivariate LSTM  RMSE: ${rmse_multi:.2f}")

models = ["Naive Baseline", "Univariate LSTM", "Multivariate LSTM"]

mae_values = [naive_mae, mae, mae_multi]
rmse_values = [naive_rmse, rmse, rmse_multi]

plt.figure(figsize=(9, 5))

plt.bar(models, mae_values)

plt.title("MAE Comparison")
plt.ylabel("MAE ($)")

plt.tight_layout()
plt.show()

plt.figure(figsize=(9, 5))

plt.bar(models, rmse_values)

plt.title("RMSE Comparison")
plt.ylabel("RMSE ($)")

plt.tight_layout()
plt.show()

df["Daily_Return"] = df["Close"].pct_change()

print(df[["Date", "Close", "Daily_Return"]].head())

print("Mean Daily Return:", round(df["Daily_Return"].mean() * 100, 3), "%")
print("Daily Volatility:", round(df["Daily_Return"].std() * 100, 3), "%")
print("Minimum Daily Return:", round(df["Daily_Return"].min() * 100, 2), "%")
print("Maximum Daily Return:", round(df["Daily_Return"].max() * 100, 2), "%")

df["Rolling_Volatility"] = (
    df["Daily_Return"]
    .rolling(window=30)
    .std()
)

print(df[["Date", "Rolling_Volatility"]].tail())

plt.figure(figsize=(12, 5))

plt.plot(
    df["Date"],
    df["Rolling_Volatility"] * 100
)

plt.title("AAPL 30-Day Rolling Volatility")
plt.xlabel("Date")
plt.ylabel("Volatility (%)")

plt.tight_layout()
plt.show()

vol_threshold = df["Rolling_Volatility"].quantile(0.75)

df["High_Volatility"] = (
    df["Rolling_Volatility"] >= vol_threshold
).astype(int)

print("High-volatility threshold:",
      round(vol_threshold * 100, 2), "%")

print(
    df["High_Volatility"].value_counts()
)

return_threshold = df["Daily_Return"].abs().quantile(0.95)

df["Large_Movement"] = (
    df["Daily_Return"].abs() >= return_threshold
).astype(int)

print(
    "Large-movement threshold:",
    round(return_threshold * 100, 2),
    "%"
)

print(
    df["Large_Movement"].value_counts()
)

test_dates = df["Date"].iloc[split:].reset_index(drop=True)

results = pd.DataFrame({
    "Date": test_dates,
    "Actual": actual_multi.flatten(),
    "Predicted": predicted_multi.flatten()
})

results["Absolute_Error"] = (
    abs(results["Actual"] - results["Predicted"])
)

print(results.head())

volatility_data = df[
    ["Date", "Rolling_Volatility", "High_Volatility"]
].copy()

results = results.merge(
    volatility_data,
    on="Date",
    how="left"
)

print(results.head())

normal_error = results.loc[
    results["High_Volatility"] == 0,
    "Absolute_Error"
].mean()

high_vol_error = results.loc[
    results["High_Volatility"] == 1,
    "Absolute_Error"
].mean()

print("Average error during normal volatility:",
      round(normal_error, 2))

print("Average error during high volatility:",
      round(high_vol_error, 2))

correlation = results[
    ["Absolute_Error", "Rolling_Volatility"]
].corr().iloc[0, 1]

print(
    "Correlation between forecast error and volatility:",
    round(correlation, 3)
)

